version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "-"
